# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/placement_portal
spring.datasource.username=postgres
spring.datasource.password=akshaya123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081